apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: memory-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      nodeSelector:
        workload: frontend
      containers:
        - name: frontend
          image: memory-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
          env:
            - name: VITE_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: memory-game-config
                  key: VITE_BACKEND_URL
