apiVersion: v1
kind: Secret
metadata:
  name: memory-game-secret
  namespace: memory-game
type: Opaque
stringData:
  POSTGRES_USER: 'memory_user'
  POSTGRES_PASSWORD: 'memory_pass'
  POSTGRES_DB: 'memory_game'
  DATABASE_URL: 'postgres://memory_user:memory_pass@postgres-service:5433/memory_game'
  JWT_SECRET: 'supersecretkey'
