apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  PORT: "8080"
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_USER: "memory_user"
  DB_PASS: "memory_pass"
  DB_NAME: "memory_game"
  JWT_SECRET: "supersecretkey"
