apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: memory-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
